---
title: "raw-materials"
author: "Rick Gilmore"
date: "8/8/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Things psychologists would benefit from knowing more about

- What are the different measures measuring
    - Brain activity
        - EEG
        - fMRI
        - PET
    - Brain structure
        - Structural MRI
        - DTI
    - Body status
        - ECG + respiration
        - EGG, EDR
        - Endocrine
        - EMG
    - Body position (behavior)
        - Gaze tracking
        - Kinematic measurements
            - Optical
            - EM
        - Force platforms, devices
        - Video/audio
        - Button presses, mouse movements
        - Verbal responses
    - Inferred internal states
- Ideas from physics/math/engineering
    - State spaces
    - Configuration of body (joint angle space)
        - Kinematics
        - Kinetics
        - Dynamics
            - State spaces, attractors, etc.
    - Electromagnetism
        - In neurons
            - Resistance/conductance, capacitance, current, voltage, inductance
        - re: MRI, EEG
        - Properties of EM as source of information about environment (vision, electroreception, magnetoreception)
    - Time domain, frequency domain, FFT
        - Waves
        - Mechanical waves as source of information about environment (sound, touch)
    - Derivatives, integrals, differential equations
    - Network science
        - The importance of the connectome
        - The relative unimportance of the connectome
            - What is the connectivity function? Across time...
    - Digital vs. analog computing
- Some basic ideas in ethology
    - Ingestion, defense, reproduction
    - Maximize reproductive success
    - Foraging (maximize food/info intake, minimize energy expenditure)
    
## Emotion

### Fear

Pellman, B. A., & Kim, J. J. (2016). What Can Ethobehavioral Studies Tell Us about the Brain’s Fear System? Trends in Neurosciences, 39(6), 420–431. Retrieved from http://dx.doi.org/10.1016/j.tins.2016.04.001

### Reward

Navratilova, E., Atcherley, C. W., & Porreca, F. (2015). Brain Circuits Encoding Reward from Pain Relief. Trends in neurosciences, 38(11), 741–750. Retrieved from http://dx.doi.org/10.1016/j.tins.2015.09.003

## Perception

### Multisensory/binding

Bizley, J. K., Maddox, R. K., & Lee, A. K. C. (2016). Defining Auditory-Visual Objects: Behavioral Tests and Physiological Mechanisms. Trends in neurosciences, 39(2), 74–85. Retrieved January 31, 2016, from http://www.sciencedirect.com/science/article/pii/S0166223615002817


### Vision

Wandell, B. A., Dumoulin, S. O., & Brewer, A. A. (2007). Visual field maps in human cortex. *Neuron*, *56*(2), 366–383. Retrieved from http://dx.doi.org/10.1016/j.neuron.2007.10.012

Hubel, D. H. (1982). Exploration of the primary visual cortex, 1955-78. *Nature*, *299*(5883), 515–524. http://neurosciences.us/courses/systems/CentralVision/hubel82.pdf.

Hubel, D. H., & Wiesel, T. N. (1962). Receptive fields, binocular interaction and functional architecture in the cat’s visual cortex. *The Journal of Physiology*, *160*(1), 106–154. https://doi.org/10.1113/jphysiol.1962.sp006837

Kanwisher, N., McDermott, J., & Chun, M. M. (1997). The fusiform face area: a module in human extrastriate cortex specialized for face perception. *The Journal of Neuroscience: The official journal of the Society for Neuroscience*, *17*(11), 4302–4311. Retrieved from https://www.ncbi.nlm.nih.gov/pubmed/9151747

### Perception and Action

Goodale, M. A., Milner, A. D., Jakobson, L. S., & Carey, D. P. (1991). A neurological dissociation between perceiving objects and grasping them. *Nature*, *349*(6305), 154–156. https://doi.org/10.1038/349154a0

Goodale, M. A., & Milner, A. D. (1992). Separate visual pathways for perception and action. *Trends in Neurosciences*, *15*(1), 20–25. https://doi.org/10.1016/0166-2236(92)90344-8

### Mind-reading

Kay, K. N., Naselaris, T., Prenger, R. J., & Gallant, J. L. (2008). Identifying natural images from human brain activity. *Nature*, *452*(7185), 352–355. https://doi.org/10.1038/nature06713. [Supplemental materials](http://www.nature.com/nature/journal/v452/n7185/extref/nature06713-s1.pdf).

Kay, K. N., & Gallant, J. L. (2009). I can see what you see. *Nature Neuroscience*, *12*(3), 245–245. https://doi.org/10.1038/nn0309-245

## Learning/plasticity

Bonin, R. P., & De Koninck, Y. (2015). Reconsolidation and the regulation of plasticity: moving beyond memory. Trends in neurosciences, 38(6), 336–344. Retrieved from http://dx.doi.org/10.1016/j.tins.2015.04.007

### NMDA receptor

Banerjee, A., Larsen, R. S., Philpot, B. D., & Paulsen, O. (2016). Roles of Presynaptic NMDA Receptors in Neurotransmission and Plasticity. Trends in neurosciences, 39(1), 26–39. Retrieved from http://dx.doi.org/10.1016/j.tins.2015.11.001

## Disorder

### Depression

Yirmiya, R., Rimmerman, N., & Reshef, R. (2015). Depression as a microglial disease. Trends in neurosciences, 38(10), 637–658. Retrieved from http://dx.doi.org/10.1016/j.tins.2015.08.001

## Neuroanatomy

### Motor cortex

Barbas, H., & García-Cabezas, M. Á. (2015). Motor cortex layer 4: less is more. Trends in neurosciences, 38(5), 259–261. Retrieved from http://dx.doi.org/10.1016/j.tins.2015.03.005

### Insula

Namkung, H., Kim, S.-H., & Sawa, A. (2017). The Insula: An Underestimated Brain Area in Clinical Neuroscience, Psychiatry, and Neurology. Trends in neurosciences, 40(4), 200–207. Retrieved from http://dx.doi.org/10.1016/j.tins.2017.02.002

### Claustrum

Goll, Y., Atlan, G., & Citri, A. (2015). Attention: the claustrum. Trends in neurosciences, 38(8), 486–495. Retrieved from http://dx.doi.org/10.1016/j.tins.2015.05.006

## Microbiome

Sarkar, A., Lehto, S. M., Harty, S., Dinan, T. G., Cryan, J. F., & Burnet, P. W. J. (2016). Psychobiotics and the Manipulation of Bacteria-Gut-Brain Signals. Trends in neurosciences, 39(11), 763–781. Retrieved from http://dx.doi.org/10.1016/j.tins.2016.09.002

## Resting state/DMN/Connectome

Swanson, L. W., & Lichtman, J. W. (2016). From Cajal to Connectome and Beyond. Annual review of neuroscience, 39, 197–216. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-071714-033954>

Raichle, M. E. (2015). The brain’s default mode network. Annual review of neuroscience, 38, 433–447. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-071013-014030>.

