---
title: "Schedule"
---

---

## Week 1

### Wed, Aug 22

- Topics
    + Structure of the course, Read BW[^1] 1:1-21.
    + Does neuroscience need behavior? Does behavioral science need the brain?
    + Methods in neuroscience
- Readings
    - (recommended) Krakauer, J. W., Ghazanfar, A. A., Gomez-Marin, A., MacIver, M. A., & Poeppel, D. (2017). Neuroscience needs behavior: Correcting a reductionist bias. Neuron, 93(3), 480–490. Retrieved from http://dx.doi.org/10.1016/j.neuron.2016.12.041
    - <https://en.wikibooks.org/wiki/Cognitive_Psychology_and_Cognitive_Neuroscience/Behavioural_and_Neuroscience_Methods>.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-08-22-intro-methods.html) | [PDF](lectures/511-2018-08-22-intro-methods.pdf)
    + More on [MRI physics](https://www.youtube.com/watch?v=Ok9ILIYzmaY)

### Fri, Aug 24

- Topics
    + Methods in neuroscience, Read BW[^1] 2:51-57, 3:88-92.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-08-25-functional-methods.html) | [PDF](lectures/511-2018-08-25-functional-methods.pdf)
    + <https://en.wikibooks.org/wiki/Cognitive_Psychology_and_Cognitive_Neuroscience/Behavioural_and_Neuroscience_Methods>
    + (Optional) Cohen, M. X. (2017). Where Does EEG Come From and What Does It Mean? *Trends in Neurosciences*, *40*(4), 208–218. Retrieved from <http://dx.doi.org/10.1016/j.tins.2017.02.004>
    + (Optional) Logothetis, N. K., Pauls, J., Augath, M., Trinath, T., & Oeltermann, A. (2001). Neurophysiological investigation of the basis of the fMRI signal. *Nature*, *412*(6843), 150–157. Retrieved January 20, 2016, from <http://www.nature.com/nature/journal/v412/n6843/abs/412150a0.html>
    + (Optional) Hillman, E. M. C. (2014). Coupling mechanism and significance of the BOLD signal: a status report. *Annual Review of Neuroscience*, *37*, 161–181. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-071013-014111>.

---

## Week 2

### Wed, Aug 29

- Topics
    + Neuroanatomy. Read BW[^1] 2:36-51.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-08-29-anatomy.html) | [PDF](lectures/511-2018-08-29-anatomy.pdf)
 
### Fri, Aug 31

- Topics
    + Neuroanatomy. Read BW[^1] 2:36-51.
- Materials
   + Lecture notes | [HTML slides](lectures/511-2018-08-29-anatomy.html#42) | [PDF](lectures/511-2018-08-29-anatomy.pdf)

---

## Week 3

### Wed, Sep 5

- Topics
    + Wrap-up on neuroanatomy
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-09-05-anatomy-II.html) | [PDF](lectures/511-2018-09-05-anatomy-II.pdf)

### Fri, Sep 7

- Topics
    + **Neuroanatomy Lab**.
- Materials
    + Neuranatomy lab [handout](handouts/neuroanatomy-lab-handout.pdf)

---

## Week 4

### Wed, Sep 12

- Topics
    + Cellular neuroanatomy. Read BW 2:24-35. 
- Reading
    + Zeng, H., & Sanes, J. R. (2017). Neuronal cell-type classification: challenges, opportunities and the path forward. *Nature Reviews Neuroscience*. Retrieved from <http://dx.doi.org/10.1038/nrn.2017.85>.
    + Oliveira, J. F., Sardinha, V. M., Guerra-Gomes, S., Araque, A., & Sousa, N. (2015). Do stars govern our actions? Astrocyte involvement in rodent behavior. *Trends in Neurosciences*, *38*(9), 535–549. Retrieved from http://dx.doi.org/10.1016/j.tins.2015.07.006
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-09-12-cells.html) | [PDF](lectures/511-2018-09-12-cells.pdf)

### Fri, Sep 14

- Topics
    + **Quiz 1**. | [Download](quiz/quiz-01/511-18-quiz-01.pdf) |. Due at start of class on Friday, September 21, 2018.
    + Neurophysiology. Read BW 3:61-78.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-09-14-neurophys.html) | [PDF](lectures/511-2018-09-14-neurophys.pdf)

---

## Week 5

### Wed, Sep 19

**NO CLASS**

### Fri, Sep 21

- Quiz-01 due. [Submit here](https://psu.instructure.com/courses/1942232/assignments/10392150).
- Topics
    + Neural communication. Read BW 3:78-92.
    + Neurochemistry. Read BW: 4:95-100.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-09-21-neurophys-II.html) | [PDF](lectures/511-2018-09-21-neurophys-II.pdf)

---

## Week 6

### Wed, Sep 26

- Topics
    + Neurochemistry II. Read BW 4:101-130.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-09-26-neurochemistry-II.html) | [PDF](lectures/511-2018-09-26-neurochemistry-II.pdf)

### Fri, Sep 28

- Topic
    - Hormones. 5:125-154. Read BW 5:131-159.
    - Brain/gut connection
- Reading
    - Sarkar, A., Lehto, S. M., Harty, S., Dinan, T. G., Cryan, J. F., & Burnet, P. W. J. (2016). Psychobiotics and the manipulation of bacteria-gut-brain signals. *Trends in Neurosciences*, *39*(11), 763–781. Retrieved from http://dx.doi.org/10.1016/j.tins.2016.09.002
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-09-28-hormones.html) | [PDF](lectures/511-2018-09-26-neurochemistry-II.pdf)

---

## Week 7

### Wed, Oct 3

- Topics
    + Evolution & Development. Read BW 6 & 7. 
- Reading
    + Optional [Hofman 2014](http://www.frontiersin.org/Journal/Abstract.aspx?s=742&name=neuroanatomy&ART_DOI=10.3389/fnana.2014.00015).
    + Rakic, P. (2009). Evolution of the neocortex: a perspective from developmental biology. Nature Reviews Neuroscience, 10(10), 724–735. Retrieved October 5, 2015, from <http://www.nature.com/nrn/journal/v10/n10/abs/nrn2719.html>.
    + Cao, M., Huang, H., & He, Y. (2017). Developmental connectomics from infancy through early childhood. *Trends in Neurosciences*, *40*(8), 494–506. Retrieved from <http://dx.doi.org/10.1016/j.tins.2017.06.003>
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-10-03-evo-devo.html) | [PDF](lectures/511-2018-10-03-evo-devo.pdf)

### Fri, Oct 5

**NO CLASS**

---

## Week 8

### Wed, Oct 10

- Topics
    + Brain development.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-10-10-evo-devo-II.html) | [PDF](lectures/511-2018-10-10-evo-devo-II.pdf)

### Fri, Oct 12

- Topics
    + Perception. Read BW 8:230-241.
- Reading
    + Murray, M. M., Lewkowicz, D. J., Amedi, A., & Wallace, M. T. (2016). Multisensory Processes: A Balancing Act across the Lifespan. *Trends in Neurosciences*, *39*(8), 567–579. Retrieved July 28, 2016, from http://www.sciencedirect.com/science/article/pii/S0166223616300480
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-10-12-perception.html)

---

## Week 9

### Wed, Oct 17

- Topics
    + Perception and Action. Read BW 10: 301:335, 11: 341:368.
- Reading
    + Nielsen, J. B. (2016). Human Spinal Motor Control. *Annual Review of Neuroscience*, *39*, 81–101. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-070815-013913>
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-10-17-perception-action.html) | [PDF](lectures/511-2018-10-17-perception-action.pdf)

### Fri, Oct 19

- Topics
    + Action II
    + **Quiz 2** distributed. | [Download](quiz/quiz-02/MYNAME-511-quiz-02.docx) |. Due at start of class on Friday, October 26, 2018.
- Reading
    + Shenoy, K. V., Sahani, M., & Churchland, M. M. (2013). Cortical control of arm movements: A dynamical systems perspective. *Annual Review of Neuroscience*, *36*, 337–359. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-062111-150509>.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-10-19-action-II.html) | [PDF slides](lectures/511-2018-10-19-action-II.pdf)

---

## Week 10

### Wed, Oct 24

- Topics
    + Cognition & language. Read BW 19.
- Reading
    + Hagoort, P., & Indefrey, P. (2014). The neurobiology of language beyond single words. *Annual Review of Neuroscience*, *37*, 347–362. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-071013-013847>.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-10-24-cognition-language.html) | [PDF slides](lectures/511-2018-10-24-cognition-language.pdf)

### Fri, Oct 26

- Topics
    + Learning & memory. Read BW 17.
- Reading
    + Squire, L. R., & Wixted, J. T. (2011). The cognitive neuroscience of human memory since H.M. *Annual Review of Neuroscience*, *34*, 259–288. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-061010-113720>.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-10-26-memory.html) | [PDF slides](lectures/511-2018-10-26-memory.pdf)

---

## Week 11

### Wed, Oct 31

- Topic
    + Emotion. Read BW 15.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-10-31-emotion.html) | [PDF slides](lectures/511-2018-10-31-emotion.pdf)
- Readings
        + Pellman, B. A., & Kim, J. J. (2016). What Can Ethobehavioral Studies Tell Us about the Brain’s Fear System? *Trends in Neurosciences*, *39*(6), 420–431. Retrieved from <http://dx.doi.org/10.1016/j.tins.2016.04.001>
        + Hu, H. (2016). Reward and Aversion. *Annual Review of Neuroscience*, *39*, 297–324. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-070815-014106>

### Fri, Nov 2

- Topics
    + Fear, stress, & reward. Read BW 15.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-11-02-fear-stress-reward.html) | [PDF slides](lectures/511-2018-11-02-fear-stress-reward.pdf)
- Readings
    + Musazzi, L., Tornese, P., Sala, N., & Popoli, M. (2017). Acute or Chronic? A Stressful Question. *Trends in Neurosciences*. Retrieved from <http://dx.doi.org/10.1016/j.tins.2017.07.002>
    + Watabe-Uchida, M., Eshel, N., & Uchida, N. (2017). Neural Circuitry of Reward Prediction Error. *Annual Review of Neuroscience*, *40*, 373–394. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-072116-031109>

---

## Week 12

### Wed, Nov 7

- Topics
    + Disorder and Disease. Read BW 16.
- Reading
    + Hunt, M. J., Kopell, N. J., Traub, R. D., & Whittington, M. A. (2017). Aberrant Network Activity in Schizophrenia. *Trends in Neurosciences*, *40*(6), 371–382. Retrieved from <http://dx.doi.org/10.1016/j.tins.2017.04.003>
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-11-07-schizophrenia.html) | [PDF ](lectures/511-2018-11-07-schizophrenia.pdf)

### Fri, Nov 9

- Topics
    + Disorder and Disease. Read BW 16.
- Reading
    + Pawluski, J. L., Lonstein, J. S., & Fleming, A. S. (2017). The neurobiology of postpartum anxiety and depression. *Trends in Neurosciences*, *40*(2), 106–120. Retrieved from <http://dx.doi.org/10.1016/j.tins.2016.11.009>
    + Namkung, H., Kim, S.-H., & Sawa, A. (2017). The insula: An underestimated brain area in clinical neuroscience, psychiatry, and neurology. *Trends in Neurosciences*, *40*(4), 200–207. Retrieved from <http://dx.doi.org/10.1016/j.tins.2017.02.002>
    + Volk, L., Chiu, S.-L., Sharma, K., & Huganir, R. L. (2015). Glutamate synapses in human cognitive disorders. *Annual Review of Neuroscience*, *38*, 127–149. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-071714-033821>
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-11-09-depression.html) | [PDF](lectures/511-2018-11-09-depression.pdf)

---

## Week 13

### Wed, Nov 14

- Topics
    + Networks all the way down
- Supplemental Materials
    + Swanson, L. W., & Lichtman, J. W. (2016). From Cajal to Connectome and Beyond. *Annual Review of Neuroscience*, *39*, 197–216. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-071714-033954>
    + Raichle, M. E. (2015). The brain’s default mode network. *Annual Review of Neuroscience*, *38*, 433–447. Retrieved from <http://dx.doi.org/10.1146/annurev-neuro-071013-014030>.
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-11-14-networks.html) | [PDF](lectures/511-2018-11-14-networks.pdf)

### Fri, Nov 16

- Topics
    - Reproducibility in neuroscience
    + **Quiz 3**. | [Download](quiz/quiz-03/511-quiz-03.docx) |. Due at start of class on **Friday, November 30, 2018**.
- Readings
    - Gilmore, R. O., Diaz, M. T., Wyble, B. A., & Yarkoni, T. (2017). Progress toward openness, transparency, and reproducibility in cognitive neuroscience. *Annals of the New York Academy of Sciences*. Retrieved from http://dx.doi.org/10.1111/nyas.13325
    - Gorgolewski, K. J., & Poldrack, R. A. (2016). A practical guide for improving transparency and reproducibility in neuroimaging research. *PLoS Biology*, *14*(7), e1002506. Retrieved October 2, 2016, from http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002506
- Materials
    + Lecture notes | [HTML slides](lectures/511-2018-11-16-reproducibility.html)
    
---

## Thanksgiving Break, November 19 - 23, 2018

---

## Week 14

### Wed, Nov 28

- Topics
    - Prep for student presentations

### Fri, Nov 30

- Topics
    - Prep for student presentations

---

## Week 15

### Wed, Dec 5

- Topics
    - Student presentation Group A
        - Measuring brain & behavior: Kelley, Anna, Alison, Lauren, Rhea
            - Shaffer, F., McCraty, R., & Zerr, C. L. (2014). A healthy heart is not a metronome: an integrative review of the heart’s anatomy and heart rate variability. *Frontiers in Psychology*, *5*, 1040. Retrieved from http://dx.doi.org/10.3389/fpsyg.2014.01040. | [PDF](lectures/pdf/Shaffer+et+al+(2014).pdf) |.
            - Holmes, A. J., & MacDonald, A. W. III. (accepted). Concepts and principles of clinical
functional magnetic resonance imaging. In A. G. C. Wright & M. N. Hallquist (Eds.), *Handbook of Research Methods in Clinical Psychology*. Cambridge, UK: Cambridge University Press. | [PDF](lectures/pdf/Holmes_MacDonald_fMRI_Chapter_Accepted_Jul2018.pdf) |.
    - Student presentation Group B
        - Development, aging, & plasticity: Liz, Michael, Lia, Chloe, & Nate
            - Brody, G. H., Gray, J. C., Yu, T., Barton, A. W., Beach, S. R. H., Galván, A., MacKillop, J., et al. (2017). Protective prevention effects on the association of poverty With brain development. *JAMA Pediatrics*, *171*(1), 46–52. jamanetwork.com. Retrieved from http://dx.doi.org/10.1001/jamapediatrics.2016.2988. | [PDF](lectures/pdf/Brody+et+al.,+2017+-+Protective+Prevention+Effects+on+the+Association+of+Poverty+With+Brain+Development.pdf) |.
            - Blakemore, S.-J., Burnett, S., & Dahl, R. E. (2010). The role of puberty in the developing adolescent brain. *Human Brain Mapping*, *31*(6), 926–933. Wiley Online Library. Retrieved from http://dx.doi.org/10.1002/hbm.21052. | [PDF](lectures/pdf/Blakemore,+Burnett,+&+Dahl,+2010+-+Role+of+Puberty+in+Developing+Adolescent+Brain.pdf) |.

### Fri, Dec 7

- Topics
    - Student presentation Group C
        - Cognition & Emotion: Austen, Brandon, Shane, & Natalia
            - Olff, M., Langeland, W., & Gersons, B. P. R. (2005). Effects of appraisal and coping on the neuroendocrine response to extreme stress. *Neuroscience and Biobehavioral Reviews*, *29*(3), 457–467. Elsevier. Retrieved from http://dx.doi.org/10.1016/j.neubiorev.2004.12.006. | [PDF](lectures/pdf/Appraisal&NeuroendocrineResponse.pdf) |.
            - Etkin, A., Büchel, C., & Gross, J. J. (2015). The neural bases of emotion regulation. *Nature Reviews Neuroscience*, *16*(11), 693–700. nature.com. Retrieved from http://dx.doi.org/10.1038/nrn4044. | [PDF](lectures/pdf/The_neural_bases_of_emotion_re.pdf) |.
            - Gee, D. G., Humphreys, K. L., Flannery, J., Goff, B., Telzer, E. H., Shapiro, M., Hare, T. A., et al. (2013). A developmental shift from positive to negative connectivity in human amygdala–prefrontal circuitry. *The Journal of Neuroscience: The official journal of the Society for Neuroscience*, *33*(10), 4584–4593. Society for Neuroscience. Retrieved December 5, 2018, from http://www.jneurosci.org/content/33/10/4584.short.
    - Student presentation Group D
        - Neurodegeneration & disorder: Kaitlin, Sam, Daryl, & Emily
            - Wajda, D. A., & Sosnoff, J. J. (2015). Cognitive-motor interference in multiple sclerosis: A systematic review of evidence, correlates, and consequences. *BioMed Research International*, 2015, 720856. hindawi.com. Retrieved from http://dx.doi.org/10.1155/2015/720856. | [PDF](lectures/pdf/Cognitive motor interference in MS.pdf) |.
            - Bobholz, J. & Gremley, S. (2011). Multiple sclerosis and other demyelinating disorders. 10.1007/978-0-387-76978-3_20. |  [PDF](lectures/pdf/Bobholz & Gremley.MS ch.2011.pdf) |.

## Week 16

### Wed, Dec 12

- Resource [write-up/review papers](evaluation.html) due by **noon**.

[^1]: BW refers to the Behavioral Neuroscience text by Breedlove and Watson.
