---
title: "Student interests"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Rhea Banerjee

Collura, Thomas F,PhD., B.C.N., Wigton, Nancy L, PhD, LPC,Q.E.E.G.D., B.C.N., Zalaquett, Carlos,PhD., L.M.H.C., Chatters-Smith, S., & Bonnstetter, R. J., PhD. (2016). The value of EEG-based electromagnetic tomographic analysis in human performance and mental health. *Biofeedback (Online)*, *44*(2), 58-65. doi:http://dx.doi.org.ezaccess.libraries.psu.edu/10.5298/1081-5937-44.2.03

Flaisch, T., Häcker, F., Renner, B., & Schupp, H. T. (2011). Emotion and the processing of symbolic gestures: an event-related brain potential study. *Social Cognitive & Affective Neuroscience*, *6*(1), 109-118. doi:10.1093/scan/nsq022

### Key terms and concepts

- Electromagnetic tomographic analysis (ETA) including all its forms – LORETA, sLORETA, eLORETA and other variants;
- the concept of voxels and what specific numbers of voxels mean; 
- Validating [Ipsative](https://www.psychometrictest.org.uk/ipsative-items/) Decision-making with Electroencephalography (on page 61).
- Early posterior negativity (EPN) and late positive potential (LPP)
- the P1 component
- the whole section below the title “ERP data acquisition and analysis” on page 111.

## Chloe Bliton

Lamm, C., & Majdandžić, J. (2015). The role of shared neural activations, mirror neurons, and morality in empathy–A critical comment. *Neuroscience Research*, *90*, 15-24. doi:http://dx.doi.org.ezaccess.libraries.psu.edu/10.1016/j.neures.2014.10.008

Praszkier, R. (2016). Empathy, mirror neurons and SYNC. *Mind & Society*, *15*(1), 1-25. doi:http://dx.doi.org.ezaccess.libraries.psu.edu/10.1007/s11299-014-0160-x

### Key terms and concepts

- I am fascinated with the construct of empathy. At a basic level, empathy is critical to interpersonal functioning. Thus, I am interested in how empathy occurs (e.g., social learning, neural processes) and the outcomes of a lack of empathy/apathy. 
- I am curious about the role mirror neurons play (or do not play) in the interpersonal experience of empathy.
- A relatively new concept to me is brain-to-brain coupling, which I understand as synchronization of two brains through environmental cues. However, this process of syncing still seems mystical to me.

## Samantha English

Langner, R., Leiberg, S., Hoffstaedter, F., & Eickhoff, S. B. (2018). Towards a human self-regulation system: Common and distinct neural signatures of emotional and behavioural control. *Neuroscience & Biobehavioral Reviews*, *90*, 400-410. doi: 10.1016/j.neubiorev.2018.04.022

Dörfel, D., Lamke, J. P., Hummel, F., Wagner, U., Erk, S., & Walter, H. (2014). Common and differential neural networks of emotion regulation by detachment, reinterpretation, distraction, and expressive suppression: a comparative fMRI investigation. *Neuroimage*, *101*, 298-309. doi: 10.1016/j.neuroimage.2014.06.051

### Key terms and concepts

- Voxel-wise difference
- Probabilistic cytoarchitectonic maps
- Hierarchical cluster analysis

## Kelley Gunther

Merz, E., Tottenham, N., & Noble, K. (2017). Socioeconomic Status, Amygdala Volume, and Internalizing Symptoms in Children and Adolescents. *Journal of Clinical Child and Adolescent Psychology*, *2*, 1-12. doi: 10.1080/15374416.2017.1326122

Silvers, J.A., Goff, B., Gabard-Durnam, L.J., Gee, D.G., Fareri, D.S., Caldera, C., Tottenham, N. (2017). Vigilance, the amygdala, and anxiety in youth with a history of institutional care. *Biological Psychiatry: Cognitive Neuroscience and Neuroimaging*, *2*(6), 493-501. doi: http://dx.doi.org/10.1016/j.bpsc.2017.03.016 

### Key terms and concepts

- Amygdala reactivity/overreactivity to fearful stimuli
- Connectivity between prefrontal cortex and limbic system; top-down control of reactivity
- What does amygdala volume actually mean for the way that the amygdala may function and relate to behavior?

## Nate Hall

Diaconescu, A. O., Litvak, V., Mathys, C., Kasper, L., Friston, K. J., & Stephan, K. E. (2017). A computational hierarchy in human cortex. *ArXiv:1709.02323 [q-Bio]*. Retrieved from http://arxiv.org/abs/1709.02323

Friston, K. (2010). The free-energy principle: A unified brain theory? *Nature Reviews Neuroscience*, *11*(2), 127–138. https://doi.org/10.1038/nrn2787

### Key terms and concepts

-	Social cognition and the “neural architecture” of the self 
-	Computational models of appetitive motivation
-	Cortico-striatal-thalamic loops
    -	Further, functional specificity for each of these “stages” in the loop

## Brandon Patallo

Cecil, C. A., Lysenko, L. J., Jaffee, S. R., Pingault, J. B., Smith, R. G., Relton, C. L., ... & Barker, E. D. (2014). Environmental risk, Oxytocin Receptor Gene (OXTR) methylation and youth callous-unemotional traits: a 13-year longitudinal study. *Molecular Psychiatry*, *19*(10), 1071.  https://doi.org/10.1038/mp.2014.95  

Van Loey, N. E., Hofland, H. W. C., Vlig, M., Vandermeulen, E., Rose, T., Beelen, R. H. J., & Ulrich, M. M. W. (2018). Associations between traumatic stress symptoms, pain and bio-active components in burn wounds. *Psychoneuroendocrinology*.  https://doi.org/10.1016/j.psyneuen.2018.05.037

## Kaitlin Riegler 

Duff, J. (2004). The Usefulness of Quantitative EEG(QEEG) and Neurotherapy in the Assessment and Treatment of Post-concussion Syndrome. *Clinical EEG and Neuroscience*, *35*(4). https://doi-org.ezaccess.libraries.psu.edu/10.1177/155005940403500410

Hunter, L. E., Branch, C. A., & Lipton, M. L. (2018). The neurobiological effects of repetitive head impacts in collision sports. *Neurobiology of Disease*, (May), 0–1. https://doi.org/10.1016/j.nbd.2018.06.016.

### Key terms and concepts

- Neurotherapy (EEG biofeedback)-specifically how this process works and how can it be applied to treatment of post-concussion syndrome (other treatments more broadly)
- Metabolic cascade and the window of vulnerability caused by physiological changes following concussion
- The impact of head injury on the blood brain barrier (so the impact at the more micro level/neuronal level) and subsequent clinical implications of this. How can these changes at the neural level compare to clinically observed behavior?

## Lia Rosenstein

Mier, D., Lis, S., Esslinger, C., Sauer, C., Hagenhoff, M., Ulferts, J., . . . Kirsch, P. (2012). Neuronal correlates of social cognition in borderline personality disorder. *Scan*, *8*, 531–537. doi:10.1093/scan/nss028.

Minzenberg, M. J., Fan, J., New, A. S., Tang, C. Y., & Siever, L. J. (2007). Fronto-limbic dysfunction in response to facial emotion in borderline personality disorder: An event-related fMRI study. *Psychiatry Research-Neuroimaging*, *155*(3), 231–243. doi:10.1016/j.pseychresns.2007.03.006 

### Key terms and concepts

-	What is involved in pre-processing fMRI data?
-	What does it mean if something was “small volume corrected?”
-	ROI analyses
-	What are the ACC sub-regions?
-	What is hemodynamic activation?
-	What is serotonergic activity?

## Michael Sanders

Pavlakis, A. E., Noble, K., Pavlakis, S. G., Ali, N., & Frank, Y. (2015). Brain imaging and electrophysiology biomarkers: Is there a role in poverty and education outcome research? *Pediatric Neurology*, 52(4), 383-388. https://doi.org/10.1016/j.pediatrneurol.2014.11.005

Lee, V., & Hoaken, P. N. (2007). Cognition, emotion, and neurobiological development: Mediating the relation between maltreatment and aggression. *Child Maltreatment*, *12*(3), 281-298. https://doi.org/10.1177/1077559507303778

### Key terms

- Diffusion Tensor Imaging
- Gamma and Theta power in EEG studies
- DLPFC's role in perseverative functioning

## Alison Schreiber

Wilson, R. C., & Niv, Y. (2015). Is model fitting necessary for model-based fMRI?. *PLoS Computational Biology*, 11(6), e1004237.
https://doi.org/10.1371/journal.pcbi.1004237

King-Casas, B., & Chiu, P. H. (2012). Understanding interpersonal function in psychiatric illness through multiplayer economic games. *Biological Psychiatry*, 72(2), 119-125.
https://doi.org/10.1016/j.biopsych.2012.03.033

### Key terms and concepts 

- Neuropeptides
- Tryptophan and serotonergic systems
- Bandit Tasks

## Emily Taverna

Rasmusson, A. M., Vasek, J., Lipschitz, D. S., Vojvoda, D., Mustone, M. E., Shi, Q., ... & Charney, D. S. (2004). An increased capacity for adrenal DHEA release is associated with decreased avoidance and negative mood symptoms in women with PTSD. *Neuropsychopharmacology*, *29*(8), 1546.

Szeszko, P. R., Lehrner, A., & Yehuda, R. (2018). Glucocorticoids and hippocampal structure and function in PTSD. *Harvard Review of Psychiatry*, *26*(3), 142-157. doi: 10.1097/HRP.0000000000000188

### Key terms and concepts

- HPA axis
- glucocorticoids/ACTH/DHEA/cortisol
- hippocampus

## Austen Trainer

Kim, Sang Hee, and Stephan Hamann. Neural Correlates of Positive and Negative Emotion Regulation (2007). *Journal of Cognitive Neuroscience*, *19*(5), 776–798, https://doi.org/10.1162/jocn.2007.19.5.776 

Ochsner, Kevin N., and James J. Gross. (2008). Cognitive Emotion Regulation. *Current Directions in Psychological Science*, 17(2), 153–158, https://doi.org/10.1111/j.1467-8721.2008.00566.x

### Key terms and concepts

- The general neurobiology of emotion. 
- The distinct neurobiological correlates of emotional valence and discrete emotions (e.g., the neurobiological differences of positive v. negative emotions, more specifically fear v. anger, etc.)
- The neural correlates of various cognitive emotion regulation strategies (e.g., the neurobiology of distraction or cognitive reappraisal, emotion regulation across positive and negative emotion valence, etc.)  

## Natalia Van Doren

Barrett, L. F., & Wager, T. D. (2006). The Structure of Emotion. *Current Directions in Psychological Science*, *15*(2), 79-83. doi:10.1111/j.0963-7214.2006.00411.x

Vytal, K., & Hamann, S. (2010). Neuroimaging Support for Discrete Neural Correlates of Basic Emotions: A Voxel-based Meta-analysis. *Journal of Cognitive Neuroscience*, *22*(12), 2864-2885. doi:10.1162/jocn.2009.21366

### Key terms and concepts

- To what extent and how does the researcher hypotheses influence the decisions on were to draw the line in terms of what regions / voxels to analyze? Given the lack of consistency across researchers, it seems like voxel-hacking could occur, and it’s unclear to me what criteria are used to make these decisions about parsing voxels in a way that is not biased towards the research question.
- How can we evaluate “distinct neural correlates”? What criteria are used to determine ‘distinctness’, and what is a sufficient criteria to say that a neural correlate is distinct? Part of the debate here seems to be about how this information is interpreted. For example, Barrett and Wager argue the patterns are not distinct because they are more general to approach / withdraw systems; whereas Vital and Hamann argue that patterns are distinct because they differ from other emotional activation patterns in a statistically significant manner. Given that multiple functions are performed by any given area or network of the brain, it seems odd in the Barrett paper to make the argument that because the patterns of activation of certain emotions are also associated with approach and withdrawal that it renders these emotions as indistinct in terms of activation patterns.
- Both papers bring up the notion of consistency of activation, and draw opposite conclusions. I’m interested in learning more about how to evaluate consistency—what is considered a ’consistent’ pattern of activation? Are there specific thresholds that should be reached?

## Lauren Vasquez

Doom, J. R., Doyle, C. M., & Gunnar, M. R. (2017). Social stress buffering by friends in childhood and adolescence: Effects on HPA and oxytocin activity. *Social Neuroscience*, *12*(1), 8-21. doi: 10.1080/17470919.2016.1149095

Esposito, E. A., Jones, M. J., Doom, J. R., MacIsaac, J. L., Gunnar, M. R., & Kobor, M. S. (2016). Differential DNA methylation in peripheral blood mononuclear cells in adolescents exposed to significant early but not later childhood adversity. *Development and Psychopathology*, *28*(4pt2), 1385-1399. https://doi.org/10.1017/S0954579416000055

### Key terms and concepts

- Hypothalamic Pituitary Adrenal (HPA) axis activity
- oxytocin activity
- DNA methylation

## Shane Wise

Hipp, J. F., & Siegel, M. (2013). Dissociating neuronal gamma-band activity from cranial and ocular muscle activity in EEG. *Frontiers in Human Neuroscience*, 7, 338.  doi: 10.3389/fnhum.2013.00338

McClure, E. B., Adler, A., Monk, C. S., Cameron, J., Smith, S., Nelson, E. E., ... & Pine, D. S. (2007). fMRI predictors of treatment outcome in pediatric anxiety disorders. *Psychopharmacology*, *191*(1), 97-105.  doi:10.1016/j.biopsych.2005.08.012

### Key terms and concepts

- Beamforming
- Independent Components Analysis (ICA)
- epoch rejection
- Subject numbers. Could they get away with n=15 now? 
- Correcting slice data for slice timing and motion
- Smooth vs Unsmoothed data

## Elizabeth Youatt

Harrewijn, A. van der Molen, M.J.W., van Vliet, I.M., Tissier, R.L.M., Westenburg, P.M. (2018) Behavioral and EEG responses to social evaluation: A two-generation family study on social anxiety. *Neuroimage: Clinical*, *17*(2018), 549-562. Retrieved from https://doi.org/10.1016/j.nicl.2017.11.010

Kahle, S., Utendale, W.T., Widaman, K.F., Hastings, P.D. (2018) Parasympathetic regulation and inhibitory control predict the development of externalizing problems in early childhood. *Journal of Abnormal Child Psychology*, *46*(2), 237-249. Retrieved from https://link.springer.com/article/10.1007/s10802-017-0305-6 

### Key terms and concepts

- EEG/ERP
- social anxiety
- genetic predispositions to psychopathology
- emotion regulation
- Respiratory Sinus Arrhythmia (RSA) measures and implications
- biological functioning of the parasympathetic nervous system.