---
title: "Student interests"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Chloe Bliton

Lamm, C., & Majdandžić, J. (2015). The role of shared neural activations, mirror neurons, and morality in empathy–A critical comment. *Neuroscience Research*, *90*, 15-24. doi:http://dx.doi.org.ezaccess.libraries.psu.edu/10.1016/j.neures.2014.10.008

Praszkier, R. (2016). Empathy, mirror neurons and SYNC. *Mind & Society*, *15*(1), 1-25. doi:http://dx.doi.org.ezaccess.libraries.psu.edu/10.1007/s11299-014-0160-x

### Key terms and concepts

- I am fascinated with the construct of empathy. At a basic level, empathy is critical to interpersonal functioning. Thus, I am interested in how empathy occurs (e.g., social learning, neural processes) and the outcomes of a lack of empathy/apathy. 
- I am curious about the role mirror neurons play (or do not play) in the interpersonal experience of empathy.
- A relatively new concept to me is brain-to-brain coupling, which I understand as synchronization of two brains through environmental cues. However, this process of syncing still seems mystical to me.

## Samantha English

Langner, R., Leiberg, S., Hoffstaedter, F., & Eickhoff, S. B. (2018). Towards a human self-regulation system: Common and distinct neural signatures of emotional and behavioural control. *Neuroscience & Biobehavioral Reviews*, *90*, 400-410. doi: 10.1016/j.neubiorev.2018.04.022

Dörfel, D., Lamke, J. P., Hummel, F., Wagner, U., Erk, S., & Walter, H. (2014). Common and differential neural networks of emotion regulation by detachment, reinterpretation, distraction, and expressive suppression: a comparative fMRI investigation. *Neuroimage*, *101*, 298-309. doi: 10.1016/j.neuroimage.2014.06.051

### Key terms and concepts

- Voxel-wise difference
- Probabilistic cytoarchitectonic maps
- Hierarchical cluster analysis

## Kelley Gunther

Merz, E., Tottenham, N., & Noble, K. (2017). Socioeconomic Status, Amygdala Volume, and Internalizing Symptoms in Children and Adolescents. *Journal of Clinical Child and Adolescent Psychology*, *2*, 1-12. doi: 10.1080/15374416.2017.1326122

Silvers, J.A., Goff, B., Gabard-Durnam, L.J., Gee, D.G., Fareri, D.S., Caldera, C., Tottenham, N. (2017). Vigilance, the amygdala, and anxiety in youth with a history of institutional care. *Biological Psychiatry: Cognitive Neuroscience and Neuroimaging*, *2*(6), 493-501. doi: http://dx.doi.org/10.1016/j.bpsc.2017.03.016 

### Key terms and concepts

- Amygdala reactivity/overreactivity to fearful stimuli
- Connectivity between prefrontal cortex and limbic system; top-down control of reactivity
- What does amygdala volume actually mean for the way that the amygdala may function and relate to behavior?

## Nate Hall

Diaconescu, A. O., Litvak, V., Mathys, C., Kasper, L., Friston, K. J., & Stephan, K. E. (2017). A computational hierarchy in human cortex. ArXiv:1709.02323 [q-Bio]. Retrieved from http://arxiv.org/abs/1709.02323

Friston, K. (2010). The free-energy principle: A unified brain theory? *Nature Reviews Neuroscience*, *11*(2), 127–138. https://doi.org/10.1038/nrn2787

### Key terms and concepts

-	Social cognition and the “neural architecture” of the self 
-	Computational models of appetitive motivation
-	Cortico-striatal-thalamic loops
    -	Further, functional specificity for each of these “stages” in the loop

## Kaitlin Riegler 

Duff, J. (2004). The Usefulness of Quantitative EEG(QEEG) and Neurotherapy in the Assessment and Treatment of Post-concussion Syndrome. *Clinical EEG and Neuroscience*, *35*(4). https://doi-org.ezaccess.libraries.psu.edu/10.1177/155005940403500410

Hunter, L. E., Branch, C. A., & Lipton, M. L. (2018). The neurobiological effects of repetitive head impacts in collision sports. *Neurobiology of Disease*, (May), 0–1. https://doi.org/10.1016/j.nbd.2018.06.016.

### Key terms and concepts

- Neurotherapy (EEG biofeedback)-specifically how this process works and how can it be applied to treatment of post-concussion syndrome (other treatments more broadly)
- Metabolic cascade and the window of vulnerability caused by physiological changes following concussion
- The impact of head injury on the blood brain barrier (so the impact at the more micro level/neuronal level) and subsequent clinical implications of this. How can these changes at the neural level compare to clinically observed behavior?

## Alison Schreiber

Wilson, R. C., & Niv, Y. (2015). Is model fitting necessary for model-based fMRI?. *PLoS Computational Biology*, 11(6), e1004237.
https://doi.org/10.1371/journal.pcbi.1004237

King-Casas, B., & Chiu, P. H. (2012). Understanding interpersonal function in psychiatric illness through multiplayer economic games. *Biological Psychiatry*, 72(2), 119-125.
https://doi.org/10.1016/j.biopsych.2012.03.033

### Key terms and concepts 

- Neuropeptides
- Tryptophan and serotenergic systems
- Bandit Tasks

## Emily Taverna

Rasmusson, A. M., Vasek, J., Lipschitz, D. S., Vojvoda, D., Mustone, M. E., Shi, Q., ... & Charney, D. S. (2004). An increased capacity for adrenal DHEA release is associated with decreased avoidance and negative mood symptoms in women with PTSD. *Neuropsychopharmacology*, *29*(8), 1546.

Szeszko, P. R., Lehrner, A., & Yehuda, R. (2018). Glucocorticoids and hippocampal structure and function in PTSD. *Harvard Review of Psychiatry*, *26*(3), 142-157. doi: 10.1097/HRP.0000000000000188

### Key terms and concepts

- HPA axis
- glucocorticoids/ACTH/DHEA/cortisol
- hippocampus

## Natalia Van Doren

Barrett, L. F., & Wager, T. D. (2006). The Structure of Emotion. Current Directions in Psychological Science,15(2), 79-83. doi:10.1111/j.0963-7214.2006.00411.x

Vytal, K., & Hamann, S. (2010). Neuroimaging Support for Discrete Neural Correlates of Basic Emotions: A Voxel-based Meta-analysis. *Journal of Cognitive Neuroscience*, *22*(12), 2864-2885. doi:10.1162/jocn.2009.21366

### Key terms and concepts

- To what extent and how does the researcher hypotheses influence the decisions on were to draw the line in terms of what regions / voxels to analyze? Given the lack of consistency across researchers, it seems like voxel-hacking could occur, and it’s unclear to me what criteria are used to make these decisions about parsing voxels in a way that is not biased towards the research question.
- How can we evaluate “distinct neural correlates”? What criteria are used to determine ‘distinctness’, and what is a sufficient criteria to say that a neural correlate is distinct? Part of the debate here seems to be about how this information is interpreted. For example, Barrett and Wager argue the patterns are not distinct because they are more general to approach / withdraw systems; whereas Vital and Hamann argue that patterns are distinct because they differ from other emotional activation patterns in a statistically significant manner. Given that multiple functions are performed by any given area or network of the brain, it seems odd in the Barrett paper to make the argument that because the patterns of activation of certain emotions are also associated with approach and withdrawal that it renders these emotions as indistinct in terms of activation patterns.
- Both papers bring up the notion of consistency of activation, and draw opposite conclusions. I’m interested in learning more about how to evaluate consistency—what is considered a ’consistent’ pattern of activation? Are there specific thresholds that should be reached?

## Elizabeth Youatt

Harrewijn, A. van der Molen, M.J.W., van Vliet, I.M., Tissier, R.L.M., Westenburg, P.M. (2018) Behavioral and EEG responses to social evaluation: A two-generation family study on social anxiety. *Neuroimage: Clinical*, *17*(2018), 549-562. Retrieved from https://doi.org/10.1016/j.nicl.2017.11.010

Kahle, S., Utendale, W.T., Widaman, K.F., Hastings, P.D. (2018) Parasympathetic regulation and inhibitory control predict the development of externalizing problems in early childhood. *Journal of Abnormal Child Psychology*, *46*(2), 237-249. Retrieved from https://link.springer.com/article/10.1007/s10802-017-0305-6 

### Key terms and concepts

- EEG/ERP
- social anxiety
- genetic predispositions to psychopathology
- emotion regulation
- RSA measures and implications
- biological functioning of the parasympathetic nervous system. 